# Generated by Django 4.0 on 2022-01-07 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_remove_post_author_remove_post_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(max_length=8, unique=True)),
                ('manufacturer', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inoperative', 'Inoperative')], max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Mileage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kilometers', models.PositiveIntegerField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mileage', to='core.vehicle')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
