# Generated by Django 4.0.1 on 2022-01-09 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(max_length=8, unique=True)),
                ('manufacturer', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inoperative', 'Inoperative')], max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Mileage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kilometers', models.PositiveIntegerField(verbose_name='mileage')),
                ('created_at', models.DateField()),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mileage', to='api.vehicle')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
