# Generated by Django 4.0.1 on 2022-01-09 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mileage',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
